-- PostgreSQL DDL for the ERD-tutor conversation tables (reference).
-- Prefer running `python run_erd_tutor_migration.py`, which generates
-- dialect-appropriate DDL (SQLite locally, PostgreSQL/Supabase in prod)
-- from the SQLAlchemy models.
CREATE TABLE IF NOT EXISTS erd_tutor_conversations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    er_lab_question_id INTEGER,
    er_diagram_question_id INTEGER,
    session_id INTEGER,
    context_type VARCHAR(20) NOT NULL,
    ibl_stage VARCHAR(40) NOT NULL DEFAULT 'orientation',
    hint_level INTEGER NOT NULL DEFAULT 1,
    misconceptions TEXT,
    current_erd_model TEXT,
    last_submit_report TEXT,
    last_submit_score TEXT,
    last_query_summary TEXT,
    last_student_goal TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (er_lab_question_id) REFERENCES er_lab_questions(id),
    FOREIGN KEY (er_diagram_question_id) REFERENCES er_diagram_questions(id),
    FOREIGN KEY (session_id) REFERENCES er_lab_sessions(id)
);
CREATE INDEX IF NOT EXISTS ix_erd_tutor_conv_lab ON erd_tutor_conversations(user_id, er_lab_question_id, session_id);
CREATE INDEX IF NOT EXISTS ix_erd_tutor_conv_standalone ON erd_tutor_conversations(user_id, er_diagram_question_id);

CREATE TABLE IF NOT EXISTS erd_tutor_messages (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    conversation_id INTEGER NOT NULL,
    role VARCHAR(20) NOT NULL,
    mode VARCHAR(10) NOT NULL,
    content TEXT,
    metadata_json TEXT,
    submission_id INTEGER,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (conversation_id) REFERENCES erd_tutor_conversations(id),
    FOREIGN KEY (submission_id) REFERENCES er_lab_submissions(id)
);
CREATE INDEX IF NOT EXISTS ix_erd_tutor_msg_conv ON erd_tutor_messages(conversation_id, created_at);
