-- PostgreSQL DDL for the course_info table (reference).
-- Prefer running `python run_course_info_migration.py`, which generates
-- dialect-appropriate DDL (SQLite locally, PostgreSQL/Azure in prod) from the
-- SQLAlchemy model. This is a single-row table (id = 1) holding the student
-- Course Info page content as Markdown, editable by staff from Settings.
CREATE TABLE IF NOT EXISTS course_info (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL
);
